// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationService.Infrastructure.Persistence;

#nullable disable

namespace ReservationService.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    [Migration("20251101091929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservationService.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BudgetPerGuest")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("EstimatedTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<string>("Occasion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeatingPreference")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReservationDate");

                    b.HasIndex("Status");

                    b.HasIndex("UserEmail");

                    b.ToTable("Reservations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c792c55-79f2-4d20-a5b9-56664fee5b8b"),
                            BudgetPerGuest = 25.5m,
                            CreatedAt = new DateTime(2024, 12, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Мария Иванова",
                            EstimatedTotal = 51m,
                            NumberOfPeople = 2,
                            Occasion = "romantic",
                            PhoneNumber = "+37360000001",
                            ReservationDate = new DateTime(2025, 1, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            SeatingPreference = "window",
                            SpecialRequests = "Свечи и цветы",
                            Status = "Confirmed",
                            UpdatedAt = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserEmail = "maria@example.com"
                        },
                        new
                        {
                            Id = new Guid("c7b75c6b-adbd-4872-83f9-82e927cbf97f"),
                            BudgetPerGuest = 18m,
                            CreatedAt = new DateTime(2024, 12, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Алексей Петров",
                            EstimatedTotal = 108m,
                            NumberOfPeople = 6,
                            Occasion = "birthday",
                            PhoneNumber = "+37360000002",
                            ReservationDate = new DateTime(2024, 12, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            SeatingPreference = "indoor",
                            SpecialRequests = "Торт и шарики",
                            Status = "Completed",
                            UpdatedAt = new DateTime(2024, 12, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserEmail = "alexey@example.com"
                        },
                        new
                        {
                            Id = new Guid("0b24b232-5d9e-4e8e-91b1-94ea0c6c0f4a"),
                            BudgetPerGuest = 32m,
                            CreatedAt = new DateTime(2024, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Елена Сидорова",
                            EstimatedTotal = 128m,
                            NumberOfPeople = 4,
                            Occasion = "business",
                            PhoneNumber = "+37360000003",
                            ReservationDate = new DateTime(2025, 1, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            SeatingPreference = "quiet",
                            SpecialRequests = "Проектор",
                            Status = "Pending",
                            UpdatedAt = new DateTime(2024, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserEmail = "elena@example.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
