using System.Collections.Concurrent;
using Feane.Contracts.Dishes;
using MenuService.Models;
using System.Linq;

namespace MenuService.Infrastructure;

internal sealed class InMemoryDishRepository : IDishRepository
{
    private readonly ConcurrentDictionary<Guid, DishDocument> _storage = new();
    private readonly Random _random = new();

    public Task<IReadOnlyCollection<DishDocument>> GetAllAsync(CancellationToken cancellationToken)
    {
        var dishes = _storage.Values
            .OrderBy(dish => dish.Name, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        return Task.FromResult<IReadOnlyCollection<DishDocument>>(dishes);
    }

    public Task<DishDocument?> GetByIdAsync(Guid id, CancellationToken cancellationToken)
    {
        _storage.TryGetValue(id, out var dish);
        return Task.FromResult(dish);
    }

    public Task<DishDocument> CreateAsync(CreateDishRequest request, CancellationToken cancellationToken)
    {
        var dish = new DishDocument
        {
            Id = Guid.NewGuid(),
            Name = request.Name,
            Description = request.Description,
            Price = request.Price,
            Category = request.Category,
            ImageUrl = request.ImageUrl,
            CreatedAt = DateTime.UtcNow
        };

        if (!_storage.TryAdd(dish.Id, dish))
        {
            throw new InvalidOperationException("Failed to add dish to the in-memory store.");
        }

        return Task.FromResult(dish);
    }

    public Task<DishDocument?> UpdateAsync(Guid id, UpdateDishRequest request, CancellationToken cancellationToken)
    {
        if (!_storage.TryGetValue(id, out var existing))
        {
            return Task.FromResult<DishDocument?>(null);
        }

        existing.Name = request.Name;
        existing.Description = request.Description;
        existing.Price = request.Price;
        existing.Category = request.Category;
        existing.ImageUrl = request.ImageUrl;
        existing.UpdatedAt = DateTime.UtcNow;

        return Task.FromResult<DishDocument?>(existing);
    }

    public Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken)
    {
        return Task.FromResult(_storage.TryRemove(id, out _));
    }

    public Task<(int created, int skipped)> SeedAsync(int count, CancellationToken cancellationToken)
    {
        var created = 0;
        var skipped = 0;

        for (var i = 0; i < count; i++)
        {
            var name = $"Sample Dish {_random.Next(1, 10_000)}";
            if (_storage.Values.Any(d => string.Equals(d.Name, name, StringComparison.OrdinalIgnoreCase)))
            {
                skipped++;
                continue;
            }

            var dish = new DishDocument
            {
                Id = Guid.NewGuid(),
                Name = name,
                Description = "Autogenerated sample dish.",
                Price = Math.Round((decimal)_random.NextDouble() * 50m, 2),
                Category = _random.Next(0, 2) == 0 ? "Food" : "Drink",
                CreatedAt = DateTime.UtcNow,
                ImageUrl = "/Images/sample.png"
            };

            _storage.TryAdd(dish.Id, dish);
            created++;
        }

        return Task.FromResult((created, skipped));
    }
}
